### ISSUE TITLE
Adding an CPU-Temperature monitor

### ISSUE THREAD

**Issue by TobiasMie** [nextcloud/serverinfo#117]
It would be nice if the CPU-Temperature would be monitored. Maybe only if it is too high.

**Comment by MorrisJobke** [comment]
Something that should be handled by a proper monitoring IMO. We should usually limit this to purely Nextcloud related stuff otherwise we re-do what monitoring solutions already provide in a far better way.

See also https://github.com/nextcloud/serverinfo/issues/116#issuecomment-378151180

I hope you can understand the reasoning behind this. Thanks for the request nevertheless
