### ISSUE TITLE
Hint to deactivation of monitor app if there is no readable

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/serverinfo#142]
Hello,

I got the following error:

`is_readable(): open_basedir restriction in effect. File(/proc/meminfo) is not within the allowed path(s): (/var/www/clients/client39/web136/web:/var/www/clients/client39/web136/private:/var/www/clients/client39/web136/tmp:/var/www/cloud/web:/srv/www/cloud/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin) at /var/www/clients/client39/web136/web/nc/apps/serverinfo/lib/SystemStatistics.php#97`

This is correct because of server setting.
In this case there are no values for logging found.

Would be better to get an info to disable the monitoring app or, for future versions change the code in serverinfo/lib/SystemStatistics.php#97 to be independently from server side phpmyadmin.

**Comment by joshtrichards** [comment]
Hi @Siggi0904 - Thanks for your report (I know it was awhile ago!). This particular code in question has changed a few times and no longer exists.

There may (read: are) still some areas that will interact with `open_basedir` (and/or `exec()`) restrictions poorly (non-silently), but there are fewer today then previously.

Since the code in question is gone I'm going to close this out. Feel free to open a new issue if you experience a similar problem with a newer version of NC.

-jr

**Comment by Siggi0904** [comment]
But it's not fixed till 26.0.3, means latest nc 26 version.

**Comment by kesselb** [comment]
Fixed for 28 via restricted mode: https://github.com/nextcloud/serverinfo#restricted-mode--nextcloud-28
