### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/serverinfo#347]
There is an error in the logs:

```
Error	no app in context	Exception: Return value of OCA\ServerInfo\OperatingSystems\DefaultOs::getTime() must be of the type string, null returned in file '/home/xxx/public_html/xxx/apps/serverinfo/lib/OperatingSystems/DefaultOs.php' line 115

    /home/xxx/public_html/xxx/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\ServerIn ... {}, "BasicData")

    /home/xxx/public_html/xxx/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main("OCA\\Server ... r", "BasicData", OC\AppFramew ... {}, { _route: "o ... "})

    /home/xxx/public_html/xxx/ocs/v1.php - line 62:

    OC\Route\Router->match("/ocsapp/app ... a")

    /home/xxx/public_html/xxx/ocs/v2.php - line 23:

    require_once("/home/xxx/p ... p")

Spowodowany TypeError: Return value of OCA\ServerInfo\OperatingSystems\DefaultOs::getTime() must be of the type string, null returned

    /home/xxx/public_html/xxx/apps/serverinfo/lib/Os.php - line 89:

    OCA\ServerInfo\OperatingSystems\DefaultOs->getTime()

    /home/xxx/public_html/xxx/apps/serverinfo/lib/Controller/ApiController.php - line 179:

    OCA\ServerInfo\Os->getTime()

    /home/xxx/public_html/xxx/lib/private/AppFramework/Http/Dispatcher.php - line 217:

    OCA\ServerInfo\Controller\ApiController->BasicData()

    /home/xxx/public_html/xxx/lib/private/AppFramework/Http/Dispatcher.php - line 126:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\ServerIn ... {}, "BasicData")

    /home/xxx/public_html/xxx/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\ServerIn ... {}, "BasicData")

    /home/xxx/public_html/xxx/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main("OCA\\Server ... r", "BasicData", OC\AppFramew ... {}, { _route: "o ... "})

    /home/xxx/public_html/xxx/ocs/v1.php - line 62:

    OC\Route\Router->match("/ocsapp/app ... a")

    /home/xxx/public_html/xxx/ocs/v2.php - line 23:

    require_once("/home/xxx/p ... p")
```

**Operating system**:
Linux 5.4.17-2102.205.7.3.el7uek.x86_64 x86_64
**Database:**
mysql 5.7.30 
**PHP version:**
7.3.25

**Nextcloud version:** (see Nextcloud admin page)
23.0.0

**App:**
Serverinfo 1.13.0

**Comment by tgressly** [comment]
+1

**Comment by joshtrichards** [comment]
I suspect this was the result of the environment your NC was/is running in having `shell_exec()` restricted and how PHP handled this in in versions <8.

In older PHP versions a warning might show up somewhere - if one had that level error reporting on - but things would silently proceeded onward. The only reason this triggered a stack trace is because NC *was* expecting a value there and got nada. In PHP >=8 it's a fatal error and wouldn't have even gotten that far.

In any case, the move on the NC side seems to be to move as much as possible away from dependence on `shell_exec()`. I created a PR that I suspect will address this issue.

That all said, I suspect you'll have other issues (or at least more limited information available) in Admin->System for the time being (at least if you're still running NC in a `shell_exec()` restricted environment). There are still spots relying `shell_exec()` for the time being.

**Comment by joshtrichards** [comment]
Since there's nothing specific to still do here the `shell_exec` stuff is already covered elsewhere, closing in favor of #169.
