### ISSUE TITLE
[Enhancement] System Info

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/serverinfo#362]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

1. It would be very helpful to add the results of `<?php phpinfo(); ?>` to the "System" page
2. It would also be useful to add the cache info to that page.

**Describe the solution you'd like**

1. Just want a quick and easy way to view `phpinfo()` w/out having to manually handle it with my own custom page that I always have to rename when not in use, and name when I need it. Since NC is already secured via credentials, having this info on the system page shouldn't be considered a risk and more than your personal pics and docs on NC.
2. I recently changed cache type from APC to Redis, and it would be very handy to see the type(s) of cache NC is recognizing, usage stats of the cache(s) and so on. Currently the System tab is fairly basic and marginally useful; this would help toward making it more useful.

**Describe alternatives you've considered**

- Manually handling a `phpinfo()` page; not easy with the architecture of NC. Also more of a time waste, having to constantly rename the file when wanting/obscuring it.
- Creating an addon for the sole purpose of adding the `php phpinfo()`. Not being a coder, and especially not being at all familiar w/NC's architecture, it would take me WAY too long to do something so simple that an NC dev could probably add literally in 30 seconds. Also, I'd have no idea whatsoever on how to add caching details.

**Additional context**

Pretty plz w/sugar on top? :-p

**Comment by joshtrichards** [comment]
Some of the caching details you may be looking for are already exposed through the serverinfo external monitoring endpoint. (You'll find the link at the bottom of your serverinfo page). Admittedly that's made for use by tools, but the data is there/gathered already. It can be accessed in both XML or JSON. That data includes - of what you requested:

- opcache statistics 
- NC's memcache local/distributed/locking configuration (though since this is a configured parameter I'm not sure how useful this is either way to expose)

In the interest of keeping the the user interface as clutter-free as possible, it might be good to explore what are the most important (and most widely useful) bits to add within the human facing interface (if any).

Personally I could see:

- opcache.revalidate_freq <-- in order to assess for server tuning as recommended in the NC Admin Manual
- Loaded PHP .ini files <-- in order to determine where one's config files are and which are active
- Possibly session.save_handler & session.save_path <-- i.e. file based, redis, etc.
- Maybe a quick ping/pong via the redis client to see if it's responding (possibly wrapped in an hrtime or similar to get an indication of latency albeit w/o any serious sampling involved) - https://github.com/phpredis/phpredis#ping
- Maybe a bit of exposure of `info()` call data from the redis client similar to what's done for the database server (i.e. version, used memory, etc.) - https://github.com/phpredis/phpredis#info
- I was tempted myself to add PHP's sys_temp_dir but it probably makes more sense to pull NC's chosen temp path since the logic for that overrides whatever PHP's sys_temp_dir is (and I have a local code change that does just that for serverinfo including providing capacity info similar to that for other "Disks")

It might also be useful to distinguish between things useful for real-time monitoring versus one-off snapshots. The latter might more properly belong under `/settings/admin/support` (aka: the System Report under Admin->Support).

**Comment by kesselb** [comment]
Implemented by https://github.com/nextcloud/serverinfo/pull/469
