### ISSUE TITLE
Add Info about CPU

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/serverinfo#44]
Hi, besides the CPU load, information about the available CPU (type, features, number of cores, etc) would be highly appreciated and will round up the serverinfo app!

regards, hitam4450

**Comment by zeugmatis** [comment]
Note that if you have SSH access to your host / server,  you can easily get this info yourself anytime using the "cpuinfo" or "cat /proc/cpuinfo" commands.  :-) 

And this would be nice but unfortunately there are some issues which appear to make it more complex: 

- No maintained PHP library to give easy way do this - which is probably why it doesn't show up in phpinfo() either.

- Could parse an external command e.g. 'cpuinfo' but this would require an exec() call which might not be good from a security standpoint.  

- Could use file_get_contents() for /proc/cpuinfo and parse that, but this too has security implications e.g. if it is ever tricked to read /etc/passwd instead of /proc/cpuinfo - or even NC's  config.php... 

- Many hosts - especially shared - have PHP's exec() / file_get_contents() functions administratively disabled or otherwise crippled in some way due to above security issues, and could result in bug reports here that have nothing to do with NC but the webhost.  

- cpuinfo and reading /proc/cpuinfo both rely on procfs which is linux specific and thus would not work on *BSD or Windows based systems.

**Comment by hitam4450** [comment]
@zeugmatis: Thank you for your comprehensive answer! 

regards, hitam4450

**Comment by nickvergessen** [comment]
Also you should normally know what hardware your stuff is running on, right? 😛 

Closing as per above
